clear all; close all;

addpath(genpath('../../../../aed_matlab_modeltools/TUFLOWFV/tuflowfv/'));

ncfile = 'W:\CIIP\Scenarios\Calibration\2017_2019\CoorongBGC_006_validation_201707_201903_wq_all.nc';

[XX,YY,nodeID,faces,X,Y,ID] = tfv_get_node_from_2dm('../../../models/HCHB/hchb_tfvaed_2019_2021_v1/model/geo/mesh/CoorongBGC_mesh_000.2dm');


fid = fopen('initial_conditions_20190101.csv','wt');

dat = tfv_readnetcdf(ncfile,'time',1);
timesteps = dat.Time;

[~,t_ind] = min(abs(timesteps - datenum(2019,01,01,00,00,00)));


rawGeo = tfv_readnetcdf(ncfile,'timestep',t_ind);


geo_x = double(rawGeo.cell_X);
geo_y = double(rawGeo.cell_Y);
dtri = DelaunayTri(geo_x,geo_y);

vars = {...
    'H',...
    'U',...
    'V',...
    'SAL',...
    'TEMP',...
    'TRACE_1',...
    'WQ_NCS_SS1',...
    'WQ_TRC_AGE',...
    'WQ_OXY_OXY',...
    'WQ_SIL_RSI',...
    'WQ_NIT_AMM',...
    'WQ_NIT_NIT',...
    'WQ_PHS_FRP',...
    'WQ_PHS_FRP_ADS',...
    'WQ_OGM_DOC',...
    'WQ_OGM_POC',...
    'WQ_OGM_DON',...
    'WQ_OGM_PON',...
    'WQ_OGM_DOP',...
    'WQ_OGM_POP',...
    'WQ_PHY_GRN',...
    'WQ_MA2_ULVA',...
    'WQ_MA2_ULVA_IN',...
    'WQ_MA2_ULVA_IP',...

    };

writevars = {...
    'WL',...
    'U',...
    'V',...
    'SAL',...
    'TEMP',...
    'TRACE_1',...
    'WQ_1',...
    'WQ_2',...
    'WQ_3',...
    'WQ_4',...
    'WQ_5',...
    'WQ_6',...
    'WQ_7',...
    'WQ_8',...
    'WQ_9',...
    'WQ_10',...
    'WQ_11',...
    'WQ_12',...
    'WQ_13',...
    'WQ_14',...
    'WQ_15',...
    'WQ_16',...
    'WQ_17',...
    'WQ_18',...
    };



fprintf(fid,'ID,');
for i = 1:length(vars)

    if i == length(vars)
        fprintf(fid,'%s\n',writevars{i});
    else
        fprintf(fid,'%s,',writevars{i});
    end
end

for i = 1:length(ID)
    
    pnt(1,1) = X(i);
    pnt(1,2) = Y(i);

    temp = nearestNeighbor(dtri,pnt);
    temp2 = find(rawGeo.idx2==temp);
    pnt_id = max(temp2);
    
    fprintf(fid,'%d,',ID(i));
    
    for j = 1:length(vars)
        if isfield(rawGeo,vars{j})
            
          if strcmpi(vars{j},'H') == 1  
              pdata =  rawGeo.(vars{j})(temp);
          else
              pdata =  rawGeo.(vars{j})(pnt_id);
          end
        else
           pdata = 0;
        end
        
%         if strcmpi(vars{j},'H') == 1
%             pdata = 0.043;
%         end
        
        if j == length(vars)
            fprintf(fid,'%4.4f\n',pdata);
        else
            fprintf(fid,'%4.4f,',pdata);
        end
    end
end

fclose(fid);
    

