# Appendix B {-}

           
          
           
```{r A-testing, echo=FALSE, message=FALSE, warning=FALSE}
library(knitr)
library(kableExtra)
library(readxl)
library(rmarkdown)



theSheet_Names <- list.files(path = "HTML/longterm_performance_2013_2019", pattern = NULL, all.files = FALSE,
           full.names = FALSE, recursive = FALSE,
           ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)

theSheet <- paste("<",'a href="HTML/longterm_performance_2013_2019/',theSheet_Names,'"',">",theSheet_Names,"<",'/a',">", sep = "")

#theSheet <- append(theSheets,'Validation 2013 2016',0)


kbl(theSheet, caption = "Model Results for longterm_performance_2013_2019", align = "l",escape = F,col.names = 'Validation 2013 2019', ) %>%

row_spec(0, background = "#14759e", bold = TRUE, color = "white") %>%
  kable_styling(full_width = T,font_size = 10) %>%
    scroll_box(fixed_thead = FALSE)
```
<br>

## Sensitivity assessment {-}


```{r A-sentbl, echo=FALSE, message=FALSE, warning=FALSE}
library(knitr)
library(kableExtra)
library(readxl)
library(rmarkdown)
theSheet <- read_excel('tables/CIIP_phase2_scenarios.xlsx', sheet = 1)
theSheet <- theSheet[theSheet$Table == "Data",]
theSheetGroups <- unique(theSheet$Group)


kbl(theSheet[,3:8], caption = "Summary of Sediment Nutrient Flux scenario settings", align = "l",) %>%
  pack_rows(theSheetGroups[1],
            min(which(theSheet$Group == theSheetGroups[1])),
            max(which(theSheet$Group == theSheetGroups[1])),
            background = '#ebebeb') %>%
  pack_rows(theSheetGroups[2],
            min(which(theSheet$Group == theSheetGroups[2])),
            max(which(theSheet$Group == theSheetGroups[2])),
            background = '#ebebeb') %>%
  pack_rows(theSheetGroups[3],
          min(which(theSheet$Group == theSheetGroups[3])),
          max(which(theSheet$Group == theSheetGroups[3])),
          background = '#ebebeb') %>%
  pack_rows(theSheetGroups[4],
          min(which(theSheet$Group == theSheetGroups[4])),
          max(which(theSheet$Group == theSheetGroups[4])),
          background = '#ebebeb') %>%
row_spec(0, background = "#14759e", bold = TRUE, color = "white") %>%
  kable_styling(full_width = T,font_size = 11) %>%
  scroll_box(fixed_thead = FALSE)
```
<br>

```{r A-sentbl2, echo=FALSE, message=FALSE, warning=FALSE}
library(knitr)
library(kableExtra)
library(readxl)
library(rmarkdown)
theSheet <- read_excel('tables/CIIP_phase2_scenarios.xlsx', sheet = 3)
theSheet <- theSheet[theSheet$Table == "Data",]
theSheetGroups <- unique(theSheet$Group)


kbl(theSheet[,3:6], caption = "T & I 1.3 Sediemnt Flux Data", align = "l",) %>%
  pack_rows(theSheetGroups[1],
            min(which(theSheet$Group == theSheetGroups[1])),
            max(which(theSheet$Group == theSheetGroups[1])),
            background = '#ebebeb') %>%
  pack_rows(theSheetGroups[2],
            min(which(theSheet$Group == theSheetGroups[2])),
            max(which(theSheet$Group == theSheetGroups[2])),
            background = '#ebebeb') %>%
  pack_rows(theSheetGroups[3],
          min(which(theSheet$Group == theSheetGroups[3])),
          max(which(theSheet$Group == theSheetGroups[3])),
          background = '#ebebeb') %>%
  pack_rows(theSheetGroups[4],
          min(which(theSheet$Group == theSheetGroups[4])),
          max(which(theSheet$Group == theSheetGroups[4])),
          background = '#ebebeb') %>%
row_spec(0, background = "#14759e", bold = TRUE, color = "white") %>%
  kable_styling(full_width = T,font_size = 11) %>%
  scroll_box(fixed_thead = FALSE)
```
<br>




```{r A-nutsen, echo=FALSE, message=FALSE, warning=FALSE}
library(knitr)
library(kableExtra)
library(readxl)
library(rmarkdown)



theSheet_Names <- list.files(path = "HTML/Sed_Nut_flux_sensitivity", pattern = NULL, all.files = FALSE,
           full.names = FALSE, recursive = FALSE,
           ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)

theSheet <- paste("<",'a href="HTML/Sed_Nut_flux_sensitivity/',theSheet_Names,'"',">",theSheet_Names,"<",'/a',">", sep = "")

#theSheet <- append(theSheets,'Nutrient Sensitivity',0)


kbl(theSheet, caption = "Model Results for Nutrient Sensitivity", align = "l",escape = F,col.names = 'Nutrient Sensitivity', ) %>%

row_spec(0, background = "#14759e", bold = TRUE, color = "white") %>%
  kable_styling(full_width = T,font_size = 10) %>%
    scroll_box(fixed_thead = FALSE)
```

### Sensitivity to internal nutrient loading {-}
