%% define vars in processing

% 3D vars name for C pool
NPool_3D={'WQ_OGM_DOP',...
    'WQ_OGM_POP',...
    'WQ_PHS_FRP',...
    'WQ_PHS_FRP_ADS',...
    'WQ_DIAG_PHY_TPHY',...
    'WQ_DIAG_PHY_IP',...
    'WQ_MAG_ULVA_C_IP',...
    };
NPool_3D_factors=[1 1 1 1 1/106 1 1]*31/1e9;

% 2D vars name for C pool
NPool_2D={'WQ_DIAG_MAC_MAC_BEN',...
    'WQ_DIAG_MAG_IP_BEN',...
    'WQ_DIAG_PHY_MPB_BEN',...
    'MPB_BENXPC',...
    };
NPool_2D_factors=[1/106 1 1/106 1]*31/1e9;

% 3D vars name for C BGC process
N_BGC_3D={'WQ_DIAG_PHY_DINO_SET_P',...
    'WQ_DIAG_PHY_DIATOM_SET_P',...
    'WQ_DIAG_PHY_CRYPT_SET_P',...
    'WQ_DIAG_PHY_GRN_SET_P',...
    'WQ_DIAG_OGM_POP_SET',...
    'WQ_DIAG_PHY_UPT_PO4'          ,...
    'WQ_DIAG_OGM_POP_HYD',...
    'WQ_DIAG_OGM_DOP_MIN',...
    'WQ_DIAG_PHY_SET',...
    'PHY_SET2_P',...
    'PHY_SETXPC',...
    };

% 'WQ_DIAG_PHY_DINO_MOR_P',...
%     'WQ_DIAG_PHY_DIATOM_MOR_P',...
%     'WQ_DIAG_PHY_CRYPT_MOR_P',...
%     'WQ_DIAG_PHY_GRN_MOR_P',...
%     'WQ_DIAG_PHY_DINO_EXC_P',...
%     'WQ_DIAG_PHY_DIATOM_EXC_P',...
%     'WQ_DIAG_PHY_CRYPT_EXC_P',...
%     'WQ_DIAG_PHY_GRN_EXC_P',...
%     
N_BGC_3D_factors=[1 1 1 1 1 1 1 1 1/106 1 1]*31/1e9;

% 2D vars name for BGC process
N_BGC_2D={'MPB_RESXPC',...
    'WQ_DIAG_OGM_POP_SWI',...
    'WQ_DIAG_OGM_DOP_SWI',...
    'WQ_DIAG_PHS_FRP_DSF',...
    'WQ_DIAG_OGM_POP_RES',...
    'WQ_DIAG_PHS_DIP_ATM',...
    'WQ_DIAG_MAG_MAG_SWI_P',...
    'WQ_DIAG_MAG_MAG_SWI_C',...
    'WQ_DIAG_PHY_MPB_GPP',...
    'WQ_DIAG_PHY_MPB_RSP',...
    'WQ_DIAG_PHY_MPB_RES',...
    'WQ_DIAG_PHY_PHY_SWI_C',...
    'WQ_DIAG_PHY_PHY_SWI_P',...
    };
N_BGC_2D_factors=[1 1 1 1 1 1 1 0.001 1/106 1/106 1/106 1/106 1 ]*31/1e9;
%N_BGC_2D_perSecond={...
%    'WQ_DIAG_PHY_PSED_PHY',...
%    'WQ_DIAG_OGM_PSED_PON',...
%    };

%% plotting setting

% all C pool var names in the plot
NPool_vars ={'WQ_PHS_FRP',...
    'WQ_PHS_FRP_ADS',...
    'WQ_OGM_DOP',...
    'WQ_OGM_POP',...
    'WQ_MAG_ULVA_C_IP',...
    'WQ_DIAG_MAG_IP_BEN',...
    'MPB_BENXPC',...
    'WQ_DIAG_PHY_IP',...
    };

% names to display in the plot
NPool_names={'reactive phosphate',...
    'adsorbed reactive phosphate',...
    'dissolved organic phosphorus',...
    'particle organic phosphorus',...
    'phosphorus in Ulva (floating)',...
    'phosphorus in Ulva (attached)',...
    'phosphorus in benthic algae',...
    'phosphorus in phytoplankton',...
    };

% factors to convert biomass to N
NPool_factors=[1 1 1 1 1 1 1 1];

% color scheme for each variables
NPool_colors=[252,141,89;...
    227,74,51;...
    67,162,202;...
    8,81,156;...
    152,0,67;...
    0,109,44;...
    44,162,95;...
    102,194,164];



%% all BGC process var names in the plot
N_BGC_vars ={'MPB_RESXPC',...
    'WQ_DIAG_OGM_POP_RES',...
    'WQ_DIAG_PHS_FRP_DSF',...
    'WQ_DIAG_PHS_DIP_ATM',...
    'PHYTO_BURIAL_P',...
    'WQ_DIAG_MAG_MAG_SWI_C',...
    'WQ_DIAG_OGM_POP_SET',...
    };

% names to display in the plot
N_BGC_names={...
    'phosphorus in algae resuspension',...
    'particle phosphorus resuspension',...
    'sediment phosphorus release',...
    'atmosperic phosphorus deposition',...
    'phosphorus in phytoplankton burial',...
    'phosphorus in macroalgae burial',...
    'particle phosphorus sedimentation',...
    };

N_BGC_signs=[1 1 1 1 1 1 1];
N_BGC_factors=[1 1 1 1 1 0.001 1];

% color scheme for each variables
N_BGC_colors=[44,162,95;...
    67,162,202;...
    227,74,51;...
    253,187,132;...
    191,211,230;...
140,150,198;...
129,15,124];
%%
% % all BGC process var names in the plot
% N_exch_vars ={...
%     'WQ_DIAG_OGM_PON_SWI',...
%     
%     'WQ_DIAG_OGM_DON_SWI',...
% 
%     };
% 
% % names to display in the plot
% N_exch_names={...
%     'PON SWI',...
%     'PON res',...
%     'PON set',...
%     'DON SWI',...
%     'AMM DSF',...
%     'NIT DSF',...
%     'MA2 swi',...
%     };
% 
% N_exch_signs=[1 1 1 1 1 1 1];
% N_exch_factors=[1 1 1 1 1 1 1];
% 
% % color scheme for each variables
% N_exch_colors=[166,206,227;...
%     31,120,180;...
%     178,223,138;...
%     51,160,44;...
%     251,154,153;...
%     227,26,28;...
%     253,191,111;...
%     255,127,0;...
%     202,178,214;...
%     106,61,154];


%%
N_flux_vars ={'OGM_dop',...
    'OGM_pop',...
    'PHS_frp',...
    'PHS_frp_ads',...
    'PHY_grn',...
    'PHY_diatom',...
    'PHY_crypt',...
    'PHY_dino',...
    'MA2_ulva_IP',...
    };

N_flux_names={'IP',...
    'OP',...
    'PP'};

N_flux_names2={'inorganic phosphorus',...
    'organic phosphorus',...
    'phosphorus in primary producers'};

N_flux_colors=[252,141,89;...
    67,162,202;...
    0,109,44;...
    ];