%% define vars in processing

% 3D vars name for C pool
NPool_3D={'WQ_OGM_DON',...
    'WQ_OGM_PON',...
    'WQ_NIT_NIT',...
    'WQ_NIT_AMM',...
    'WQ_DIAG_PHY_TPHY',...
    'WQ_DIAG_PHY_IN',...
    'WQ_MAG_ULVA_C_IN',...
    };
NPool_3D_factors=[1 1 1 1 16/106 1 1]*14/1e9;

% 2D vars name for C pool
NPool_2D={'WQ_DIAG_MAC_MAC_BEN',...
    'WQ_DIAG_MAG_IN_BEN',...
    'WQ_DIAG_PHY_MPB_BEN',...
    'MPB_BENXNC',...
    };
NPool_2D_factors=[16/106 1 16/106 1]*14/1e9;

% 3D vars name for C BGC process
N_BGC_3D={'WQ_DIAG_NIT_DENIT',...
    'WQ_DIAG_PHY_DINO_SET_N',...
    'WQ_DIAG_PHY_DIATOM_SET_N',...
    'WQ_DIAG_PHY_CRYPT_SET_N',...
    'WQ_DIAG_PHY_GRN_SET_N',...
    'WQ_DIAG_OGM_PON_SET',...
    'WQ_DIAG_PHY_UPT_NO3'          ,...
    'WQ_DIAG_PHY_UPT_NH4'          ,...
    'WQ_DIAG_NIT_NITRIF'           ,...
    'WQ_DIAG_OGM_PON_HYD',...
    'WQ_DIAG_OGM_DON_MIN',...
    'WQ_DIAG_PHY_SET',...
    'PHY_SET2',...
    'PHY_SETXNC',...
    };
%     'WQ_DIAG_PHY_DINO_MOR_N',...
%     'WQ_DIAG_PHY_DIATOM_MOR_N',...
%     'WQ_DIAG_PHY_CRYPT_MOR_N',...
%     'WQ_DIAG_PHY_GRN_MOR_N',...
%     'WQ_DIAG_PHY_DINO_EXC_N',...
%     'WQ_DIAG_PHY_DIATOM_EXC_N',...
%     'WQ_DIAG_PHY_CRYPT_EXC_N',...
%     'WQ_DIAG_PHY_GRN_EXC_N',...

N_BGC_3D_factors=[1 1 1 1 1 1 1 1 1 1 1 16/106 1 1]*14/1e9;

% 2D vars name for BGC process
N_BGC_2D={'MPB_RESXNC',...
    'WQ_DIAG_OGM_PON_SWI',...
    'WQ_DIAG_OGM_DON_SWI',...
    'WQ_DIAG_NIT_AMM_DSF',...
    'WQ_DIAG_NIT_NIT_DSF',...
    'WQ_DIAG_OGM_PON_RES',...
    'WQ_DIAG_NIT_DIN_ATM',...
    'WQ_DIAG_MAG_MAG_SWI_N',...
    'WQ_DIAG_MAG_MAG_SWI_C',...
    'WQ_DIAG_PHY_MPB_GPP',...
    'WQ_DIAG_PHY_MPB_RSP',...
    'WQ_DIAG_PHY_MPB_RES',...
    'WQ_DIAG_PHY_PHY_SWI_C',...
    'WQ_DIAG_PHY_PHY_SWI_N',...
    };
N_BGC_2D_factors=[1 1 1 1 1 1 1 1 0.034 16/106 16/106 16/106 16/106 1 ]*14/1e9;
%N_BGC_2D_perSecond={...
%    'WQ_DIAG_PHY_PSED_PHY',...
%    'WQ_DIAG_OGM_PSED_PON',...
%    };

%% plotting setting

% all C pool var names in the plot
NPool_vars ={'WQ_NIT_NIT',...
    'WQ_NIT_AMM',...
    'WQ_OGM_DON',...
    'WQ_OGM_PON',...
    'WQ_MAG_ULVA_C_IN',...
    'WQ_DIAG_MAG_IN_BEN',...
    'MPB_BENXNC',...
    'WQ_DIAG_PHY_IN',...
    };

% names to display in the plot
NPool_names={'nitrate',...
    'ammonium',...
    'dissolved organic nitrogen',...
    'particle organic nitrogen',...
    'nitrogen in Ulva (floating)',...
    'nitrogen in Ulva (attached)',...
    'nitrogen in benthic algae',...
    'nitrogen in phytoplankton',...
    };

% factors to convert biomass to N
NPool_factors=[1 1 1 1 1 1 1 1];

% color scheme for each variables
NPool_colors=[252,141,89;...
    227,74,51;...
    67,162,202;...
    8,81,156;...
    152,0,67;...
    0,109,44;...
    44,162,95;...
    102,194,164];



%% all BGC process var names in the plot
N_BGC_vars ={'MPB_RESXNC',...
    'WQ_DIAG_OGM_PON_RES',...
    'WQ_DIAG_NIT_AMM_DSF',...
    'WQ_DIAG_NIT_DIN_ATM',...
    'WQ_DIAG_NIT_NIT_DSF',...
    'WQ_DIAG_NIT_DENIT',...
    'PHYTO_BURIAL',...
    'WQ_DIAG_MAG_MAG_SWI_C',...
    'WQ_DIAG_OGM_PON_SET',...
    };

% names to display in the plot
N_BGC_names={...
'nitrogen in algae resuspension',...
    'particle nitrogen resuspension',...
    'sediment nitrogen release',...
    'atmosperic nitrogen deposition',...
    'sediment denitrification',...
    'pelagic denitrification',...
    'nitrogen in phytoplankton burial',...
    'nitrogen in macroalgae burial',...
    'particle nitrogen sedimentation',...

    };

N_BGC_signs=[1 1 1 1 1 1 1 1 1 1 1 1];
N_BGC_factors=[1 1 1 1 1 1 1 0.034 1];

% color scheme for each variables
N_BGC_colors=[44,162,95;...
    67,162,202;...
    227,74,51;...
    253,187,132;...
    191,211,230;...
158,188,218;...
140,150,198;...
136,86,167;...
129,15,124];
%%
% % all BGC process var names in the plot
% N_exch_vars ={...
%     'WQ_DIAG_OGM_PON_SWI',...
%     
%     'WQ_DIAG_OGM_DON_SWI',...
% 
%     };
% 
% % names to display in the plot
% N_exch_names={...
%     'PON SWI',...
%     'PON res',...
%     'PON set',...
%     'DON SWI',...
%     'AMM DSF',...
%     'NIT DSF',...
%     'MA2 swi',...
%     };
% 
% N_exch_signs=[1 1 1 1 1 1 1];
% N_exch_factors=[1 1 1 1 1 1 1];
% 
% % color scheme for each variables
% N_exch_colors=[166,206,227;...
%     31,120,180;...
%     178,223,138;...
%     51,160,44;...
%     251,154,153;...
%     227,26,28;...
%     253,191,111;...
%     255,127,0;...
%     202,178,214;...
%     106,61,154];


%%
N_flux_vars ={'OGM_don',...
    'OGM_pon',...
    'NIT_nit',...
    'NIT_amm',...
    'PHY_grn',...
    'PHY_diatom',...
    'PHY_crypt',...
    'PHY_dino',...
    'MA2_ulva_IN',...
    };

N_flux_names={'IN',...
    'ON',...
    'PP'};

N_flux_names2={'inorganic nitrogen',...
    'organic nitrogen',...
    'nitrogen in primary producers'};

N_flux_colors=[252,141,89;...
    67,162,202;...
    0,109,44;...
    ];